




#enums/other constants
PACKET_TYPE_COMMAND  = 0
PACKET_TYPE_RESPONSE = 1
PACKET_TYPE_MESSAGE  = 2

COMMAND_ESTOP  = 0
COMMAND_COLOUR = 1
COMMAND_ESTOP_RELEASE = 2
COMMAND_FRONT=3
COMMAND_CCW=4
COMMAND_BACK=5
COMMAND_CW=6
COMMAND_MOVE_STOP=7
COMMAND_INCREASE_SPEED = 8
COMMAND_DECREASE_SPEED = 9
COMMAND_ARM_ANGLE = 10
COMMAND_ARM_SPEED = 11
COMMAND_ARM_HOME = 12
COMMAND_COLOUR_FOREVER = 13
COMMAND_SET_SPEED = 14
COMMAND_SET_TURN_SPEED = 15
COMMAND_ARM_HOME_ALL = 16
# TODO (Activity 2): define your own command type for the color sensor here.
# It must match the value you add to TCommandType in packets.h.


RESP_OK     = 0
RESP_STATUS = 1
RESP_COLOUR = 2
RESP_COLOUR_FOREVER = 3
RESP_INCREASE_SPEED = 4
RESP_DECREASE_SPEED = 5
# TODO (Activity 2): define your own response type for the color sensor here.
# It must match the value you add to TResponseType in packets.h.

STATE_RUNNING = 0
STATE_STOPPED = 1

MOVING_FORWARD = 0
MOVING_BACKWARD = 1
TURNING_CCW = 2
TURNING_CW = 3
MOVING_STOP = 4
#MOVING_STATE = MOVING_STOP


