#constants
START_MOVE_SPEED: int = 100
START_TURN_SPEED: int = 255
DRIVER_MODE_STREAMING_THRESHOLD = 0.05
LOOP_SLEEP = 0.05
START_MIN_MOVE_SPEED = 100
START_MIN_TURN_SPEED = 200
MOVE_STARTUP_DURATION = 0.1
TURN_STARTUP_DURATION = 0.1
START_JERK_MOVE_DURATION = 0.1
START_JERK_TURN_DURATION = 0.1
START_JERK_MOVE_SPEED = 120
START_JERK_TURN_SPEED = 100
START_FORCE_STOP_SPEED = 255
START_FORCE_STOP_DURATION = 0.1