PACKET_TYPE_COMMAND  = 0
PACKET_TYPE_RESPONSE = 1
PACKET_TYPE_MESSAGE  = 2

COMMAND_ESTOP  = 0
COMMAND_COLOUR = 1
COMMAND_ESTOP_RELEASE = 2
COMMAND_FRONT=3
COMMAND_CCW=4
COMMAND_BACK=5
COMMAND_CW=6
COMMAND_MOVE_STOP=7
COMMAND_INCREASE_SPEED = 8
COMMAND_DECREASE_SPEED = 9
COMMAND_ARM_ANGLE = 10
COMMAND_ARM_SPEED = 11
COMMAND_ARM_HOME = 12
COMMAND_COLOUR_FOREVER = 13
COMMAND_SET_SPEED = 14
COMMAND_SET_TURN_SPEED = 15
COMMAND_ARM_HOME_ALL = 16



RESP_OK     = 0
RESP_STATUS = 1
RESP_COLOUR = 2
RESP_COLOUR_FOREVER = 3
RESP_INCREASE_SPEED = 4 
RESP_DECREASE_SPEED = 5

STATE_RUNNING = 0
STATE_STOPPED = 1

BASE = 0
SHOULDER = 1
ELBOW = 2
GRIPPER = 3

GRIPPER_CLOSE_ANGLE = 80
GRIPPER_OPEN_ANGLE = 70
